[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = ''

[tool.pytest.ini_options]
timeout = 10
testpaths = ["tests"]
markers = ["uses_rllib", "uses_cuda", "uses_malmo"]

[tool.isort]
profile = "black"
known_first_party = ["mbag"]
known_third_party = ["ray", "torch"]
