name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pip requirements
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install flake8 black mypy pytest pytest-timeout pep8-naming

      - name: Replace RLlib with custom version
        run: |
          git clone https://github.com/cassidylaidlaw/ray
          cd ray
          git checkout fixes
          python/ray/setup-dev.py -y -s air tune train autoscaler ray_operator cloudpickle data _private scripts internal tests experimental util workflow widgets cluster_utils.py dashboard

      - name: Run flake8
        run: flake8 mbag tests
        if: ${{ always() }}

      - name: Run black
        run: black --check mbag tests
        if: ${{ always() }}

      - name: Check types
        if: ${{ always() }}
        run: |
          # Shim for this issue: https://github.com/ray-project/ray/issues/14431
          touch `python -c 'import site; print(site.getsitepackages()[0])'`/ray/py.typed
          mypy mbag tests

      - name: Run tests
        if: ${{ always() }}
        run: |
          pytest -m "not uses_rllib and not uses_malmo"